ktor {
  deployment {
    port = 8080
  }
  application {
    modules = [ no.nav.budstikka.ApplicationKt.module ]
  }
}

database {
  host = ${?BUDSTIKKA_DB_HOST}
  port = ${?BUDSTIKKA_DB_PORT}
  name = ${?BUDSTIKKA_DB_DATABASE}
  username = ${?BUDSTIKKA_DB_USERNAME}
  password = ${?BUDSTIKKA_DB_PASSWORD}
  url = "postgresql://"${database.host}":"${database.port}"/"${database.name}
  url = ${?BUDSTIKKA_DB_URL}
  sslkey = ${?BUDSTIKKA_DB_SSLKEY_PK8}

  hikari {
    maximumPoolSize = 3
    minimumIdle = 1
    connectionTimeout = 10000
    idleTimeout = 300000
    maxLifetime = 1800000
  }
}
