package no.nav.budstikka.application.logging

object MdcKeys {
    const val BACKOFF_MILLIS = "backoff_millis"
    const val CAUSE_TYPE = "cause_type"
    const val CLAIMED_ROWS_COUNT = "claimed_rows_count"
    const val CONSECUTIVE_ITEM_FAILURE_COUNT = "consecutive_item_failure_count"
    const val CONSUMER = "consumer"
    const val DELIVERY_CHANNEL = "delivery_channel"
    const val DELIVERY_COUNT = "delivery_count"
    const val DELIVERY_ID = "delivery_id"
    const val ERROR_TYPE = "error_type"
    const val EVENT_ID = "event_id"
    const val HANDLER = "handler"
    const val HEALTHY_MILLIS = "healthy_millis"
    const val KAFKA_OFFSET = "kafka_offset"
    const val LEASE_BUDGET_FRACTION = "lease_budget_fraction"
    const val MAX_ATTEMPTS = "max_attempts"
    const val MAX_BATCHES = "max_batches"
    const val MAX_ITEM_FAILURE_COUNT = "max_item_failure_count"
    const val OPERATION = "operation"
    const val PARTITION = "partition"
    const val POISON_COUNT = "poison_count"
    const val REASON = "reason"
    const val REFERENCE = "reference"
    const val REPLAYED_COUNT = "replayed_count"
    const val RESULT = "result"
    const val SKIPPED_COUNT = "skipped_count"
    const val TIMEOUT_SECONDS = "timeout_seconds"
    const val TOPIC = "topic"
    const val UNPROCESSED_ROWS_COUNT = "unprocessed_rows_count"
    const val WORKER = "worker"
}
